### ISSUE TITLE
Use `regex`, not `re`.

### ISSUE THREAD

**Issue by teward** [Charcoal-SE/SmokeDetector-ng#15]
The third party `regex` module from PyPI is considered better to use than `re`.  This is because of the way it supports Unicode and other functions.

**Comment by quartata** [comment]
It also has `\K` which is very nice. Will do.

**Comment by quartata** [comment]
https://github.com/Charcoal-SE/SmokeDetector-ng/commit/f9bac065302aaf9f5f67edee266b4f4fca22f3c9
