### ISSUE TITLE
License SmokeDetector-ng under dual Apache 2/MIT

### ISSUE THREAD

**Issue by ArtOfCode-** [Charcoal-SE/SmokeDetector-ng#19]
As with other Charcoal projects, NG should be licensed under dual Apache 2.0/MIT. This requires the agreement of:

 - [x] @ArtOfCode-
 - [x] @quartata 
 - [x] @teward 

To agree to the licensing, copy and paste the following into a comment on this issue:

> I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option, and impose no additional or further terms or conditions on my agreement to this licensing.

**Comment by ArtOfCode-** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option, and impose no additional or further terms or conditions on my agreement to this licensing.

**Comment by quartata** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option, and impose no additional or further terms or conditions on my agreement to this licensing.

**Comment by teward** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option, and impose no additional or further terms or conditions on my agreement to this licensing.

**Comment by ArtOfCode-** [comment]
c143c38ae6702cb4d6be2a9bc343554a8c341819
