### ISSUE TITLE
config.json and rooms.json need sample versions 

### ISSUE THREAD

**Issue by AWegnerGitHub** [Charcoal-SE/SmokeDetector-ng#28]
Both `config.json` and `rooms.json` need to be pulled out of the repository and replaced with `*.sample.json` versions (like `secrets.json`).

Doing this allows individual instances to update configuration and room settings without worrying about those settings being clobbered when they update from the repository.

With this change, `config.json` and `rooms.json` will need to be ignored.

**Comment by quartata** [comment]
The current ones basically are sample versions. I'll just rename them (and add some comments).

**Comment by quartata** [comment]
Tried to find a JSON module that supported comments, but it doesn't seem to work on Python 3...

**Comment by j-f1** [comment]
@quartata [`json5`](https://pypi.org/project/json5) or [`hjson`](https://pypi.org/project/hjson)?

**Comment by quartata** [comment]
Oh, cool. I'll look into it later.

**Comment by ArtOfCode-** [comment]
JSON doesn't have comments...

**Comment by quartata** [comment]
Not standard JSON obviously. But variants do (+ this new JSON 5 thing apparently)

**Comment by ferrybig** [comment]
If we are going to use "JSON with comments", it's not JSON anymore, so we require all implementations that have the potential to read these "json" files to support the custom standard. This is bad for future maintainability of the code

**Comment by Manishearth** [comment]
TOML is "json with comments". It's a superset of json which supports list-style data and comments.
